### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jazzbre/Chipmunk2D-beef#1]
Hi, thanks for this project!

I get a compilation error when trying to run the Example app:

ERROR: Expected '(' or '!' at line 16:14 in e:\Beef\beefProjects\Chipmunk2D-beef\src\Bounds.bf
  public this
             ^
ERROR: Expected method declaration at line 17:3 in e:\Beef\beefProjects\Chipmunk2D-beef\src\Bounds.bf
  {

**Comment by jazzbre** [comment]
Hey, it compiles fine here, which BeefIDE version are you using?
(I'm on nightly 10/27/2020)

**Comment by jazzbre** [comment]
Oh maybe this:
`public this {}` should't work at all.
I removed it, please try, thanks!

**Comment by Ivo-Balbaert** [comment]
I should have thought about that.
I downloaded and installed the Nightly Version 0.42.8 (Nightly 11/01/2020)  and also the most recent Chipmunk2D-beef.

This fixed the compilation error.

First, when executing the git commands, I got the error:
 E:\Beef\beefProjects\Chipmunk2D-beef>git submodule init
fatal: not a git repository (or any of the parent directories): .git
A git init fixed this.

When running the cmd file, I got:
E:\Beef\beefProjects\Chipmunk2D-beef>build_windows_vs2019.cmd
The system cannot find the path specified.
Check Visual Studio version
Using Visual Studio 2019 Community Path
Building BGFX in Visual Studio 2019

Microsoft Visual Studio 2019 Version 16.7.7.
Copyright (C) Microsoft Corp. All rights reserved.

The following files were specified on the command line:

        .build\projects\vs2019\chipmunk2d.sln

These files could not be found and will not be loaded.ErrorLevel:0
Build successful!
Press any key to continue . . .

--> I don't know if I am good at this point.

Then when running in the Beef-IDE, I get a link error:

Compiling...
Beef compilation time: 0.70s
WARNING: BF0168: The variable 'radius' is assigned but its value is never used at line 66:8 in e:\Beef\beefProjects\Chipmunk2D-beef\example\src\Program.bf
   var radius = Vector2(size, size).Length;
       ^
505 modules built, 503 object files generated
Errors: 0. Warnings: 1.
Executing: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\Hostx64\\x64/link.exe" -out:e:\Beef\beefProjects\Chipmunk2D-beef\build\Debug_Win64\Example\Example.exe E:\Beef\beefProjects\Chipmunk2D-beef/build/Debug_Win64/Chipmunk2D-beef/Chipmunk2D-beef__.lib E:\Beef\beefProjects\Chipmunk2D-beef/build/Debug_Win64/corlib/corlib__.lib E:\Beef\beefProjects\Chipmunk2D-beef/build/Debug_Win64/Example/Example__.lib netapi32.lib version.lib user32.lib E:\Beef\beefProjects\Chipmunk2D-beef/build/Debug_Win64/Example/vdata.obj -defaultlib:libcmtd e:\Beef\beefProjects\Chipmunk2D-beef\.build\win64_vs2019\bin\chipmunk2dRelease.lib -nologo -incremental:no -pdb:e:\Beef\beefProjects\Chipmunk2D-beef\build\Debug_Win64\Example\Example.pdb -debug -opt:noref -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64" -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64" -libpath:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x64" -libpath:"C:\BeefLang\bin\lib\x64" -libpath:e:\Beef\beefProjects\Chipmunk2D-beef\build\Debug_Win64\Example Beef042RT64.lib Beef042Dbg64.lib  /ignore:4099
--> **LINK : fatal error LNK1181: cannot open input file 'e:\Beef\beefProjects\Chipmunk2D-beef\.build\win64_vs2019\bin\chipmunk2dRelease.lib'**
Execution time: 0.10s
Execution Failed
ERROR: BUILD FAILED
Total build time: 0.85s

At this point I don't know how to continue. I found a .lib file here:
E:\Beef\beefProjects\Chipmunk2D-beef\build\Debug_Win64\Chipmunk2D-beef_.lib

Thanks Aleš!

**Comment by jazzbre** [comment]
I think you probably downloaded the repository instead of cloning it.
It needs to be cloned:
git clone https://github.com/jazzbre/Chipmunk2D-beef.git
or 
git clone git@github.com:jazzbre/Chipmunk2D-beef.git

And then the submodules (additional git repositories) will get cloned by running:
git submodule init
git submodule update

Now build_windows_vs2019.cmd should be run which will create .build\win64_vs2019\bin\chipmunk2dRelease.lib and will be used by Beef to link.

Hope this helps!

**Comment by Ivo-Balbaert** [comment]
Sorry to bother you so much; I got one step further:

git submodule init works and produces as output:

Submodule 'submodules/Chipmunk2D' (git@github.com:slembcke/Chipmunk2D.git) registered for path 'submodules/Chipmunk2D'
Submodule 'submodules/bx' (git://github.com/bkaradzic/bx.git) registered for path 'submodules/bx'
 
the 2nd step however gives me an error:
git submodule update
Cloning into 'E:/Beef/beefProjects/Chipmunk2D-beef/submodules/Chipmunk2D'...
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights

What can I do here?

**Comment by jazzbre** [comment]
I'm sorry :D, I see now that I used .git repositories, I converted to https and pushed.
git pull
git submodule sync
then 
git submodule init
git submodule update
and then of course build_windows_vs2019.cmd.

Thanks for testing!

**Comment by Ivo-Balbaert** [comment]
Ok, the whole sequence of prerequisites went flawlessly!

When I run the Example, I get a warning, no errors:
Executing: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\Hostx64\\x64/link.exe" -out:e:\Beef\beefProjects\Chipmunk2D-beef\build\Debug_Win64\Example\Example.exe E:\Beef\beefProjects\Chipmunk2D-beef/build/Debug_Win64/corlib/corlib__.lib E:\Beef\beefProjects\Chipmunk2D-beef/build/Debug_Win64/Chipmunk2D-beef/Chipmunk2D-beef__.lib E:\Beef\beefProjects\Chipmunk2D-beef/build/Debug_Win64/Example/Example__.lib netapi32.lib version.lib user32.lib E:\Beef\beefProjects\Chipmunk2D-beef/build/Debug_Win64/Example/vdata.obj -defaultlib:libcmtd e:\Beef\beefProjects\Chipmunk2D-beef\.build\win64_vs2019\bin\chipmunk2dRelease.lib -nologo -incremental:no -pdb:e:\Beef\beefProjects\Chipmunk2D-beef\build\Debug_Win64\Example\Example.pdb -debug -opt:noref -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64" -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64" -libpath:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x64" -libpath:"C:\BeefLang\bin\lib\x64" -libpath:e:\Beef\beefProjects\Chipmunk2D-beef\build\Debug_Win64\Example Beef042RT64.lib Beef042Dbg64.lib  /ignore:4099
   Creating library e:\Beef\beefProjects\Chipmunk2D-beef\build\Debug_Win64\Example\Example.lib and object e:\Beef\beefProjects\Chipmunk2D-beef\build\Debug_Win64\Example\Example.exp
--> LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library

I get an output of the last 500 tank positions ending with:
IT:995, P:(187.93891906738281, -159.3309326171875)
IT:996, P:(187.93891906738281, -159.3309326171875)
IT:997, P:(187.93891906738281, -159.3309326171875)
IT:998, P:(187.93891906738281, -159.3309326171875)
IT:999, P:(187.93893432617188, -159.33091735839844)

If I comment this WriteLine, I get a black console screen, no tank?

**Comment by jazzbre** [comment]
Great, so it's working. Yes there's no rendering is this example at the moment.
It's just the same example (tank) as in the original Chipmunk2D library, but running console only instead of actually rendering it on the screen.

**Comment by Ivo-Balbaert** [comment]
Great, nice to hear its working.
